[package]
name = "veriwasm"
version = "0.1.0"
authors = ["enjhnsn2 <e5johnso@eng.ucsd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaxpeax-core = {path = "yaxpeax-core"}
yaxpeax-arch = { version = "0.0.4", features = ["use-serde"] }
yaxpeax-arm = { version = "0.0.4", features = ["use-serde"] }
yaxpeax-x86 = { version = "0.0.13", features = ["use-serde"] }
"petgraph" = "0.4.13"

